/**
 * Multi Tube Views (MTV) — Centralized Model Registry
 * Contains detailed metadata for all supported AI models across providers,
 * including context limits, capabilities, input/output types, priority,
 * and fallback ordering.
 */

import { AIModelConfig, AIProviderId, AICapability } from './types.js';
import { normalizeCapability } from './capabilities.js';

export const MODEL_REGISTRY: AIModelConfig[] = [
  // --- GOOGLE GEMINI MODELS ---
  {
    id: 'gemini-3.6-flash',
    providerId: 'gemini',
    displayName: 'Gemini 3.6 Flash',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'YOUTUBE_ANALYSIS', 'SOCIAL_COPY', 'CONTENT_BRIEF', 'VISION', 'STREAMING', 'REASONING'],
    inputTypes: ['text', 'image', 'video', 'audio'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 1000000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 1,
    isDefault: true,
  },
  {
    id: 'gemini-3.6-pro',
    providerId: 'gemini',
    displayName: 'Gemini 3.6 Pro',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'YOUTUBE_ANALYSIS', 'SOCIAL_COPY', 'CONTENT_BRIEF', 'VISION', 'STREAMING', 'REASONING'],
    inputTypes: ['text', 'image', 'video', 'audio'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 2000000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 2,
    fallbackPriority: 2,
  },
  {
    id: 'gemini-1.5-flash',
    providerId: 'gemini',
    displayName: 'Gemini 1.5 Flash',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'VISION', 'STREAMING'],
    inputTypes: ['text', 'image', 'video', 'audio'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 1000000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 3,
    fallbackPriority: 3,
  },

  // --- OPENAI MODELS ---
  {
    id: 'gpt-4o-mini',
    providerId: 'openai',
    displayName: 'GPT-4o Mini',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'YOUTUBE_ANALYSIS', 'SOCIAL_COPY', 'CONTENT_BRIEF', 'VISION', 'STREAMING', 'REASONING'],
    inputTypes: ['text', 'image'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 128000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 1,
    isDefault: true,
  },
  {
    id: 'gpt-4o',
    providerId: 'openai',
    displayName: 'GPT-4o',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'YOUTUBE_ANALYSIS', 'SOCIAL_COPY', 'CONTENT_BRIEF', 'VISION', 'STREAMING', 'REASONING'],
    inputTypes: ['text', 'image'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 128000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 2,
    fallbackPriority: 2,
  },
  {
    id: 'gpt-3.5-turbo',
    providerId: 'openai',
    displayName: 'GPT-3.5 Turbo',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'SOCIAL_COPY', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 16385,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: true,
    supportsStructuredOutput: false,
    status: 'active',
    priority: 3,
    fallbackPriority: 4,
  },

  // --- XAI GROK MODELS ---
  {
    id: 'grok-2-latest',
    providerId: 'grok',
    displayName: 'Grok 2',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'SOCIAL_COPY', 'STREAMING', 'REASONING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 128000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 2,
    isDefault: true,
  },
  {
    id: 'grok-beta',
    providerId: 'grok',
    displayName: 'Grok Beta',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 128000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: false,
    supportsStructuredOutput: false,
    status: 'beta',
    priority: 2,
    fallbackPriority: 3,
  },

  // --- DEEPSEEK MODELS ---
  {
    id: 'deepseek-chat',
    providerId: 'deepseek',
    displayName: 'DeepSeek V3 (Chat)',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'SOCIAL_COPY', 'CONTENT_BRIEF', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 64000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 1,
    isDefault: true,
  },
  {
    id: 'deepseek-reasoner',
    providerId: 'deepseek',
    displayName: 'DeepSeek R1 (Reasoner)',
    capabilities: ['TEXT_GENERATION', 'REASONING', 'SEO_ANALYSIS', 'CONTENT_ANALYSIS', 'COMPETITOR_ANALYSIS'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    maxContextTokens: 64000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: false,
    supportsStructuredOutput: false,
    status: 'active',
    priority: 2,
    fallbackPriority: 2,
  },

  // --- ANTHROPIC CLAUDE MODELS ---
  {
    id: 'claude-3-5-sonnet-20241022',
    providerId: 'claude',
    displayName: 'Claude 3.5 Sonnet',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'YOUTUBE_ANALYSIS', 'SOCIAL_COPY', 'CONTENT_BRIEF', 'VISION', 'STREAMING', 'REASONING'],
    inputTypes: ['text', 'image'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 200000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 1,
    isDefault: true,
  },
  {
    id: 'claude-3-haiku-20240307',
    providerId: 'claude',
    displayName: 'Claude 3 Haiku',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'SOCIAL_COPY', 'VISION', 'STREAMING'],
    inputTypes: ['text', 'image'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 200000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 2,
    fallbackPriority: 2,
  },

  // --- MISTRAL AI MODELS ---
  {
    id: 'mistral-small-latest',
    providerId: 'mistral',
    displayName: 'Mistral Small',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'SOCIAL_COPY', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 32000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 1,
    isDefault: true,
  },
  {
    id: 'mistral-large-latest',
    providerId: 'mistral',
    displayName: 'Mistral Large',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'KEYWORD_RESEARCH', 'YOUTUBE_SEO', 'CONTENT_BRIEF', 'STREAMING', 'REASONING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 128000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 2,
    fallbackPriority: 2,
  },

  // --- OPENROUTER MODELS ---
  {
    id: 'google/gemini-3.6-flash',
    providerId: 'openrouter',
    displayName: 'OpenRouter: Gemini 3.6 Flash',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'VISION', 'STREAMING'],
    inputTypes: ['text', 'image'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 1000000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 1,
    isDefault: true,
  },
  {
    id: 'openai/gpt-4o-mini',
    providerId: 'openrouter',
    displayName: 'OpenRouter: GPT-4o Mini',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'SOCIAL_COPY', 'STREAMING'],
    inputTypes: ['text', 'image'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 128000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 2,
    fallbackPriority: 2,
  },
  {
    id: 'anthropic/claude-3.5-haiku',
    providerId: 'openrouter',
    displayName: 'OpenRouter: Claude 3.5 Haiku',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 200000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 3,
    fallbackPriority: 3,
  },
  {
    id: 'deepseek/deepseek-r1',
    providerId: 'openrouter',
    displayName: 'OpenRouter: DeepSeek R1',
    capabilities: ['TEXT_GENERATION', 'REASONING', 'CONTENT_ANALYSIS', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    maxContextTokens: 64000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: false,
    supportsStructuredOutput: false,
    status: 'active',
    priority: 4,
    fallbackPriority: 4,
  },

  // --- PUTER (OPTIONAL PROVIDER) MODELS ---
  {
    id: 'puter/gpt-4o-mini',
    providerId: 'puter',
    displayName: 'Puter: GPT-4o Mini (Optional)',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 128000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: false,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 1,
    fallbackPriority: 5,
    isDefault: true,
  },
  {
    id: 'puter/claude-3-5-sonnet',
    providerId: 'puter',
    displayName: 'Puter: Claude 3.5 Sonnet (Optional)',
    capabilities: ['TEXT_GENERATION', 'JSON_GENERATION', 'SEO_TITLE_GENERATION', 'META_DESCRIPTION', 'STREAMING'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    maxContextTokens: 200000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
    supportsToolCalling: false,
    supportsStructuredOutput: true,
    status: 'active',
    priority: 2,
    fallbackPriority: 5,
  },
];

/**
 * Get all models for a specific provider
 */
export function getModelsByProvider(providerId: AIProviderId): AIModelConfig[] {
  return MODEL_REGISTRY.filter(m => m.providerId === providerId);
}

/**
 * Find models supporting a specific capability
 */
export function getModelsForCapability(capability: AICapability | string): AIModelConfig[] {
  const norm = normalizeCapability(capability);
  return MODEL_REGISTRY.filter(m => 
    m.capabilities.includes(norm) ||
    m.capabilities.includes('TEXT_GENERATION')
  ).sort((a, b) => a.priority - b.priority);
}

/**
 * Get model config by modelId
 */
export function getModelConfig(modelId: string): AIModelConfig | undefined {
  return MODEL_REGISTRY.find(m => m.id === modelId);
}

/**
 * Get default model for a provider
 */
export function getDefaultModelForProvider(providerId: AIProviderId): string {
  const models = getModelsByProvider(providerId);
  const def = models.find(m => m.isDefault);
  return def ? def.id : (models[0]?.id || 'default');
}
